### ISSUE TITLE
Cant play the link

### ISSUE THREAD

**Issue by shqiptarial** [treshi/daily-iptv.al#1]
The link http://player-castv.c1.biz/get_m3u/piccolo-tv_channels_shqipHD.m3u

Does not work it says chek your link . Its not valid .
Maybe should take another look or i need to find another iptv player

**Comment by treshi** [comment]
prove working perfect
![Screenshot from 2020-11-24 19-37-06](https://user-images.githubusercontent.com/9460646/100137473-cfb55a00-2e8c-11eb-933c-19d7ec967933.png)

**Comment by treshi** [comment]
prove this
;http://player-castv.cf/get_m3u/piccolo-tv_channels_Albania.m3u

**Comment by shqiptarial** [comment]
This link work thank you .. faleminderit!!
